// Generated by delombok at Sat Dec 15 11:30:27 CET 2018
package net.rubenmartinez.stpc.exchange.bitso.api.websocket.domain;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
public class DiffOrdersWebsocketMessage {
	private String book;
	private long sequence;
	@JsonProperty("payload")
	private List<DiffOrder> payload;


	public static class DiffOrder {
		@JsonProperty("d")
		private Long timestamp;
		@JsonProperty("r")
		private String rate;
		@JsonProperty("t")
		private OrderType orderType;
		@JsonProperty("a")
		private String amount;
		@JsonProperty("v")
		private String value;
		@JsonProperty("o")
		private String id;
		@JsonProperty("s")
		private String status;

		public Long getTimestamp() {
			return this.timestamp;
		}

		public String getRate() {
			return this.rate;
		}

		public OrderType getOrderType() {
			return this.orderType;
		}

		public String getAmount() {
			return this.amount;
		}

		public String getValue() {
			return this.value;
		}

		public String getId() {
			return this.id;
		}

		public String getStatus() {
			return this.status;
		}

		public void setTimestamp(final Long timestamp) {
			this.timestamp = timestamp;
		}

		public void setRate(final String rate) {
			this.rate = rate;
		}

		public void setOrderType(final OrderType orderType) {
			this.orderType = orderType;
		}

		public void setAmount(final String amount) {
			this.amount = amount;
		}

		public void setValue(final String value) {
			this.value = value;
		}

		public void setId(final String id) {
			this.id = id;
		}

		public void setStatus(final String status) {
			this.status = status;
		}

		@Override
		public String toString() {
			return "DiffOrdersWebsocketMessage.DiffOrder(timestamp=" + this.getTimestamp() + ", rate=" + this.getRate() + ", orderType=" + this.getOrderType() + ", amount=" + this.getAmount() + ", value=" + this.getValue() + ", id=" + this.getId() + ", status=" + this.getStatus() + ")";
		}
	}


	public enum OrderType {
		@JsonProperty("0")
		BUY, @JsonProperty("1")
		SELL;
	}

	public String getBook() {
		return this.book;
	}

	public long getSequence() {
		return this.sequence;
	}

	public List<DiffOrder> getPayload() {
		return this.payload;
	}

	public void setBook(final String book) {
		this.book = book;
	}

	public void setSequence(final long sequence) {
		this.sequence = sequence;
	}

	public void setPayload(final List<DiffOrder> payload) {
		this.payload = payload;
	}

	@Override
	public String toString() {
		return "DiffOrdersWebsocketMessage(book=" + this.getBook() + ", sequence=" + this.getSequence() + ", payload=" + this.getPayload() + ")";
	}
}
