// Generated by delombok at Sat Dec 15 18:24:59 CET 2018
package net.rubenmartinez.stpc.app.exchange.domain;

import java.math.BigDecimal;
import java.time.ZonedDateTime;
import java.util.EnumMap;
import java.util.Map;

import org.springframework.beans.BeanUtils;

import net.rubenmartinez.stpc.exchange.domain.OrderSide;
import net.rubenmartinez.stpc.exchange.domain.Trade;

public class TaggedTrade implements Trade {

	public enum TradeTag {
		SIMULATED_BY;
	}

	private String tradeId;
	private ZonedDateTime creationDate;
	private String amount;
	private OrderSide makerSide;
	private String price;
	private EnumMap<TradeTag, String> tradeTags;

	public TaggedTrade(String tradeId, OrderSide makerSide, BigDecimal price, BigDecimal amount, ZonedDateTime creationDate) {
		this.tradeId = tradeId;
		this.makerSide = makerSide;
		this.price = price.toString();
		this.amount = amount.toString();
		this.creationDate = creationDate;
		this.tradeTags = new EnumMap<>(TradeTag.class);
	}

	public TaggedTrade(String tradeId, OrderSide side, BigDecimal price, BigDecimal amount) {
		this(tradeId, side, price, amount, ZonedDateTime.now());
	}

	public TaggedTrade(Trade trade) {
		BeanUtils.copyProperties(trade, this);
		this.tradeTags = new EnumMap<>(TradeTag.class);
	}
	
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null || getClass() != obj.getClass()) {
			return false;
		}
		TaggedTrade other = (TaggedTrade) obj;
		return other.getTradeId().equals(getTradeId());
	}

	@Override
	public int hashCode() {
		return tradeId.hashCode();
	}

	public String getTradeId() {
		return this.tradeId;
	}

	public ZonedDateTime getCreationDate() {
		return this.creationDate;
	}

	public String getAmount() {
		return this.amount;
	}

	public OrderSide getMakerSide() {
		return this.makerSide;
	}

	public String getPrice() {
		return this.price;
	}

	public Map<TradeTag, String> getTradeTags() {
		return this.tradeTags;
	}

	public void setTradeId(final String tradeId) {
		this.tradeId = tradeId;
	}

	public void setCreationDate(final ZonedDateTime creationDate) {
		this.creationDate = creationDate;
	}

	public void setAmount(final String amount) {
		this.amount = amount;
	}

	public void setMakerSide(final OrderSide makerSide) {
		this.makerSide = makerSide;
	}

	public void setPrice(final String price) {
		this.price = price;
	}

	public void setTradeTags(final EnumMap<TradeTag, String> tradeTags) {
		this.tradeTags = tradeTags;
	}

	@Override
	public String toString() {
		return "TaggedTrade(tradeId=" + this.getTradeId() + ", creationDate=" + this.getCreationDate() + ", amount=" + this.getAmount() + ", makerSide=" + this.getMakerSide() + ", price=" + this.getPrice() + ", tradeTags=" + this.getTradeTags() + ")";
	}
}
