// Generated by delombok at Sat Dec 15 11:30:27 CET 2018
package net.rubenmartinez.stpc.exchange.bitso.orderbook.dto;

import net.rubenmartinez.stpc.exchange.bitso.orderbook.helper.SortedBookOrdersMap;

public class OrderBookBeanDTO {
	private SortedBookOrdersMap asks;
	private SortedBookOrdersMap bids;
	private long sequence;

	OrderBookBeanDTO(final SortedBookOrdersMap asks, final SortedBookOrdersMap bids, final long sequence) {
		this.asks = asks;
		this.bids = bids;
		this.sequence = sequence;
	}

	public static class OrderBookBeanDTOBuilder {
		private SortedBookOrdersMap asks;
		private SortedBookOrdersMap bids;
		private long sequence;

		OrderBookBeanDTOBuilder() {
		}

		public OrderBookBeanDTOBuilder asks(final SortedBookOrdersMap asks) {
			this.asks = asks;
			return this;
		}

		public OrderBookBeanDTOBuilder bids(final SortedBookOrdersMap bids) {
			this.bids = bids;
			return this;
		}

		public OrderBookBeanDTOBuilder sequence(final long sequence) {
			this.sequence = sequence;
			return this;
		}

		public OrderBookBeanDTO build() {
			return new OrderBookBeanDTO(asks, bids, sequence);
		}

		@Override
		public String toString() {
			return "NewOrderBookSupplier.OrderBookBeanDTO.OrderBookBeanDTOBuilder(asks=" + this.asks + ", bids=" + this.bids + ", sequence=" + this.sequence + ")";
		}
	}

	public static OrderBookBeanDTOBuilder builder() {
		return new OrderBookBeanDTOBuilder();
	}

	public SortedBookOrdersMap getAsks() {
		return this.asks;
	}

	public SortedBookOrdersMap getBids() {
		return this.bids;
	}

	public long getSequence() {
		return this.sequence;
	}

	@Override
	public String toString() {
		return "NewOrderBookSupplier.OrderBookBeanDTO(asks=" + this.getAsks() + ", bids=" + this.getBids() + ", sequence=" + this.getSequence() + ")";
	}
}
