// Generated by delombok at Sat Dec 15 18:24:59 CET 2018
package net.rubenmartinez.stpc.app.exchange.decorator;

import java.math.BigDecimal;
import java.time.ZonedDateTime;

import net.rubenmartinez.stpc.app.exchange.domain.TaggedTrade;
import net.rubenmartinez.stpc.exchange.domain.OrderSide;

/**
 */
public class SimulatedTrade extends TaggedTrade {
	public SimulatedTrade(String strategyId, String tradeId, OrderSide makerSide, BigDecimal price, BigDecimal amount, ZonedDateTime creationDate) {
		super(tradeId, makerSide, price, amount, creationDate);
		getTradeTags().put(TradeTag.SIMULATED_BY, strategyId);
	}

	/**
	 * Returns the identifier of the strategy that generated this SimulatedTrade
	 */
	public String getStrategyId() {
		return getTradeTags().get(TradeTag.SIMULATED_BY);
	}

	@Override
	public String toString() {
		return "SimulatedTrade()";
	}
}
