// Generated by delombok at Sat Dec 15 11:30:27 CET 2018
package net.rubenmartinez.stpc.exchange.bitso.api.rest.domain;

import java.time.ZonedDateTime;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

import net.rubenmartinez.stpc.exchange.bitso.api.rest.deserialize.BitsoZonedDateTimeDeserializer;
import net.rubenmartinez.stpc.exchange.bitso.api.rest.deserialize.OrderSideDeserializer;
import net.rubenmartinez.stpc.exchange.domain.OrderSide;
import net.rubenmartinez.stpc.exchange.domain.Trade;

@JsonIgnoreProperties(ignoreUnknown = true)
public class BitsoRestApiTrades {
	private boolean success;
	private List<BitsoTrade> payload;
	private ZonedDateTime updated;


	public static class BitsoTrade implements Trade {
		@JsonProperty("tid")
		private String tradeId;
		@JsonProperty("book")
		private String currencyPair;
		@JsonProperty("created_at")
		@JsonDeserialize(using = BitsoZonedDateTimeDeserializer.class)
		private ZonedDateTime creationDate;
		private String amount;
		private String price;
		@JsonProperty("maker_side")
		@JsonDeserialize(using = OrderSideDeserializer.class)
		private OrderSide makerSide;

		public String getTradeId() {
			return this.tradeId;
		}

		public String getCurrencyPair() {
			return this.currencyPair;
		}

		public ZonedDateTime getCreationDate() {
			return this.creationDate;
		}

		public String getAmount() {
			return this.amount;
		}

		public String getPrice() {
			return this.price;
		}

		public OrderSide getMakerSide() {
			return this.makerSide;
		}

		public void setTradeId(final String tradeId) {
			this.tradeId = tradeId;
		}

		public void setCurrencyPair(final String currencyPair) {
			this.currencyPair = currencyPair;
		}

		public void setCreationDate(final ZonedDateTime creationDate) {
			this.creationDate = creationDate;
		}

		public void setAmount(final String amount) {
			this.amount = amount;
		}

		public void setPrice(final String price) {
			this.price = price;
		}

		public void setMakerSide(final OrderSide makerSide) {
			this.makerSide = makerSide;
		}

		@Override
		public String toString() {
			return "BitsoRestApiTrades.BitsoTrade(tradeId=" + this.getTradeId() + ", currencyPair=" + this.getCurrencyPair() + ", creationDate=" + this.getCreationDate() + ", amount=" + this.getAmount() + ", price=" + this.getPrice() + ", makerSide=" + this.getMakerSide() + ")";
		}
	}

	public boolean isSuccess() {
		return this.success;
	}

	public List<BitsoTrade> getPayload() {
		return this.payload;
	}

	public ZonedDateTime getUpdated() {
		return this.updated;
	}

	public void setSuccess(final boolean success) {
		this.success = success;
	}

	public void setPayload(final List<BitsoTrade> payload) {
		this.payload = payload;
	}

	public void setUpdated(final ZonedDateTime updated) {
		this.updated = updated;
	}

	@Override
	public String toString() {
		return "BitsoRestApiTrades(success=" + this.isSuccess() + ", payload=" + this.getPayload() + ", updated=" + this.getUpdated() + ")";
	}
}
